const fs = require('fs');

let t = require('@babel/types')

let traverse = require("@babel/traverse").default

let parser = require("@babel/parser")

let generator = require("@babel/generator").default;

const js_code = fs.readFileSync('./ruishu_hx.js', { encoding: "utf8" })

let ast = parser.parse(js_code);

var parse_obj = [
    "slice",
    "setAttribute",
    "type",
    "name",
    "call",
    "getAttribute",
    "apply",
    "string",
    "prototype",
    "href",
    "cookie",
    "https:",
    "splice",
    "parentNode",
    "hidden",
    "onloadend",
    "nodeType",
    "target",
    "HTMLGenericElement",
    "function",
    "setTimeout",
    "addEventListener",
    "charCodeAt",
    "getTime",
    "toString",
    "createElement",
    "write",
    "timeStamp",
    "location",
    "EkcP",
    "Math",
    "removeChild",
    "indexOf",
    "tagName",
    "onerror",
    "$_fh0",
    "body",
    "submit",
    "appendChild",
    "getElementById",
    "ontimeout",
    "click",
    "concat",
    "action",
    "assign",
    "input",
    "onsubmit",
    "$_fpn1",
    "onloadstart",
    "responseText",
    "eval",
    "script",
    "load",
    "wvi~qoi|wz",
    "pathname",
    "getElementsByTagName",
    "object",
    "value",
    "event",
    "innerHTML",
    "onreadystatechange",
    "$_nd",
    "method",
    "userAgent",
    "button",
    "attachEvent",
    "style",
    "external",
    "removeEventListener",
    "readyState",
    "HTMLFormElement",
    "document",
    "test",
    "protocol",
    "localStorage",
    "setInterval",
    "XMLHttpRequest",
    "onprogress",
    "onclick",
    "number",
    "form",
    "ActiveXObject",
    "showModalDialog",
    "responseType",
    "cloneNode",
    "EventTarget",
    "floor",
    "onabort",
    "onload",
    "hasOwnProperty",
    "visibility",
    "send",
    "keyCode",
    "round",
    "clientData",
    "search",
    "replace",
    "undefined",
    "open",
    "status",
    "response",
    "{ett9ger)pmgoFett9ger,sgyw5yxFett9ger1i}*s{rFett9ger1i};t",
    " srflx ",
    "stack",
    "throws",
    "mediaDevices",
    "u?uezoN0o~om~syx",
    "HTMLElement",
    "pushState",
    "_ts_",
    "func",
    "dblclick",
    "SELECT value FROM EkcP_t WHERE name=?",
    "experimental-webgl",
    "wimax",
    "\r\n",
    "FileReader",
    "standalone",
    "http://",
    "enable=true",
    "enableVertexAttribArray",
    "GetNextReqID",
    "$b_platform",
    "hg|mlixkd|kY__glY__gl:ii|g{M|qmY|hP|y;khpl|k",
    "abstract",
    "getResponseHeader",
    "instanceof",
    "callback",
    "bindBuffer",
    "c MNP-",
    "this",
    "tx~5toopy",
    "TK_STRING",
    "createOffer",
    "executeSql",
    "Mouse",
    " height=6 width=1 type=application/x-shockwave-flash src=",
    "break",
    "_DIV",
    "LOW_INT",
    "replaceChild",
    "touchstart",
    "select-",
    "y}khjxo|kxIk|gr{gzk",
    "ARRAY_BUFFER",
    "rangeMin",
    "DOMParser",
    "textBaseline",
    "hash",
    "beta",
    "__onload__",
    "'null' is not an object",
    "font",
    "#f82",
    "ownerElement",
    "kl}i}v}b}jow|ud{y",
    "unicode",
    "mozIndexedDB",
    "keyUp",
    "display",
    "statusText",
    "MediaStreamTrack",
    "scroll",
    "getUniformLocation",
    "trim",
    "unexpected number ending.",
    "<div>IE8</div>",
    "execScript",
    "GetResponseHeader",
    "Unterminated multiline comment",
    "ARSession,AudioTrackList,BeforeInstallPromptEvent.prototype.KEYUP,BlobDownloadCallback,CDATASection.prototype.remove,CSSCharsetRule,CSSPrimitiveValue.CSS_VH,CanvasRenderingContext2D.prototype.webkitGetImageDataHD,ClickData,CloseEvent.prototype.initCloseEvent,Components.interfaces.ICometMarksExtension,DeviceOrientationEvent,Function.prototype.bind,GetPerfTests,HTMLDocument.prototype.createTouchList,HTMLFormElement.prototype.requestAutocomplete,HTMLFrameSetElement.prototype.hasPointerCapture,HTMLFrameSetElement.prototype.webkitRequestFullScreen,Intl,MTT_WKSetTextSizeIndex,MediaController,MediaEncryptedEvent,Notification,Object.prototype.__defineSetter__,Object.seal,Object.setPrototypeOf,OffscreenCanvasRenderingContext2D,Path2D.prototype.addPath,PaymentResponse,PerformancePaintTiming,PresentationConnectionCloseEvent,ReaderModeArticlePage,SVGGraphicsElement.prototype.mozRequestPointerLock,SVGPatternElement.SVG_UNIT_TYPE_OBJECTBOUNDINGBOX,ScreenOrientation,SogouLoginUtils,SourceBuffer,SourceBuffer.prototype.changeType,SpeechSynthesisUtterance,TextTrackList.prototype.getTrackById,UCWebExt,WebKitFlags,_WXJS,__$_qihoo360_$__,__firefox__,__ksabCssCount,__opera,__sogou_secure_input,_double11_,chrome,chrome.app.InstallState,chrome.csi,console,defaultStatus,document.body.onmouseenter,document.body.onpage,document.body.style.backgroundBlendMode,document.body.style.lineBreak,document.body.style.minWidth,document.body.style.msTextSizeAdjust,document.body.style.textAlignLast,document.body.x-ms-acceleratorkey,document.defaultCharset,document.documentElement.onresize,document.fileCreatedDate,document.msCapsLockWarningOff,document.onmousemove,document.onselectionchange,document.scrollingElement.style.fontVariantNumeric,document.selection,document.selection.typeDetail,external,external.AddFavorite,external.IsSearchProviderInstalled,flyflow_wallpaper_js,getMatchedCSSRules,greentea,isNodeWhitespace,jesion,onerror,onmessage,onoperadetachedviewchange,openDatabase,password_manager_enabled,performance,showModalDialog,taobrowser_Event,weatherBridge,webkitAudioContext.prototype.close,webkitRequestFileSystem",
    "shaderSource",
    "#17e",
    "Msxml2.ServerXMLHTTP.6.0",
    "webkitRequestFileSystem",
    "Msxml.XMLHTTP",
    "s@qmx>xmgq~P@qmx>xmgq~JbyK /obudqF 1{zb~{x JUTOnubK",
    "|+dyh.frq/dyd.qwhuidfhEmhvlrq",
    "cookie disabled",
    "attachShader",
    "itemSize",
    "vdFm",
    "AnalyserNode",
    "eSa|TIHkcIoc_QJEMQA_",
    "{             \"iceServers\" : [                 {\"url\" : \"stun:stun01.sipphone.com\"}, {\"url\" : \"stun:stun.ekiga.net\"},                 {\"url\" : \"stun:stun.fwdnet.net\"}, {\"url\" : \"stun:stun.ideasip.com\"},                 {\"url\" : \"stun:stun.iptel.org\"}, {\"url\" : \"stun:stun.rixtelecom.se\"},                 {\"url\" : \"stun:stun.schlund.de\"}, {\"url\" : \"stun:stun.l.google.com:19302\"},                 {\"url\" : \"stun:stun1.l.google.com:19302\"}, {\"url\" : \"stun:stun2.l.google.com:19302\"},                 {\"url\" : \"stun:stun3.l.google.com:19302\"}, {\"url\" : \"stun:stun4.l.google.com:19302\"}             ]         }",
    "offsetWidth",
    "compileShader",
    "none",
    "GetAllResponseHeaders",
    "transient",
    "QTP_EPE_HOOK",
    "self",
    "onicecandidate",
    "kIyCev<}bb<ehcJeebVIe{ekCiy",
    "r__froqavera_bpav}c_s{",
    "createProgram",
    "$b_onBridgeReady",
    "link",
    "[null] is not an object",
    "match",
    "time",
    "clear",
    "TK_NAME",
    "keydown",
    ", expected ",
    "android",
    "; expires=",
    "INSERT OR REPLACE INTO EkcP_t (name, value) VALUES(?, ?)",
    "abort",
    "stringify",
    "3jeALeSsa6",
    "$b_fetchQueue",
    "STATIC_DRAW",
    "nodeValue",
    "$_f0",
    "$_cDro",
    "mouseout",
    "Msxml2.ServerXMLHTTP",
    "cellular",
    "Msxml2.XMLHTTP.4.0",
    "SEND",
    "area",
    "characterSet",
    "Function",
    "$_JQnh",
    "objectStoreNames",
    "offsetTop",
    "Microsoft.XMLHTTP.1.0",
    "frame",
    "openDatabase",
    "plugins",
    "vertexPosArray",
    "vGo~wl}rxwGH faj{ j ( wnb /j}nGHZ mnk~ppn{Z {n}~{w wnb /j}nGH L j ) POOZhGHH",
    "$_ck",
    "responseXML",
    "webkitPersistentStorage",
    "parentElement",
    "protected",
    "v|nunwr~vLnaju~j}n",
    "setRequestHeader",
    "c#r*^p#H#rklrkmrkDrkorkErkxrktrkhrkWrkJrkirkHrkurltrSD",
    "reset",
    "removeAttribute",
    "screen",
    "precision mediump float;varying vec2 varyinTexCoordinate;void main() {gl_FragColor=vec4(varyinTexCoordinate,0,1);}",
    "null",
    "chargingTime",
    "long",
    "yjk|oikuxoktzgzout",
    "base",
    "export",
    "children",
    "Keyboard",
    "getParameter",
    "msCrypto",
    "https://",
    "private",
    "enabledPlugin",
    "precision",
    "attribute vec2 attrVertex;varying vec2 varyinTexCoordinate;uniform vec2 uniformOffset;void main(){varyinTexCoordinate=attrVertex+uniformOffset;gl_Position=vec4(attrVertex,0,1);}",
    "appVersion",
    "eIkv=lla{n{j}a",
    "checked",
    "ucolus~4snnox",
    "throw",
    "refresh",
    "offsetUniform",
    "fonts",
    "x*jyv9-/K9-/",
    "hPFIexr|k[H<Q",
    "Storage",
    "webkitRTCPeerConnection",
    "password",
    "FRAGMENT_SHADER",
    "prpaerwpCtuctdwQrpaerwp_ctuctdwQrwtrz=~vx}Qstrcjae4p{{qprz",
    "try{return __filename;}catch(e){}",
    "Msxml2.XMLHTTP.3.0",
    "battery",
    "filename",
    "with",
    "languages",
    "char",
    "console",
    "a=candidate:",
    "(evaluating 'null[0]')",
    "y__loxklu~__H_loxklu~_:kgjkx5ujk",
    "jL:Nzw<okWlxnzw",
    "goto",
    "http:",
    "createObjectStore",
    "localDescription",
    "msIndexedDB",
    "GetOriginalUrl",
    "windows-1252",
    "withCredentials",
    "source",
    "parseFromString",
    "offsetHeight",
    "{\"optional\" : [ {\"RtpDataChannels\" : true} ]}",
    "clientX",
    "native",
    "c__bpgtcp_ct}js}rc*__uc~bpgtcp_ct}js}rc*__qcjclgsk_ct}js}rc*__dvbpgtcp_ct}js}rc*__bpgtcp_slup}nncb*__uc~bpgtcp_slup}nncb*__qcjclgsk_slup}nncb*__dvbpgtcp_slup}nncb*__uc~bpgtcp_qapgnr_dsla*__uc~bpgtcp_qapgnr_dl",
    "connection",
    "e__sa|~neran_ar{hq{pa",
    "_blank",
    "offsetY",
    "__anchor__",
    "<!--[if gt IE ",
    "unshift",
    "captureStackTrace",
    "HTMLEmbedElement",
    "http",
    "final",
    "Z8XHJJY.bmF0aXZlRmlVyUHJ()",
    "Illegal newline after @throw",
    "Msxml2.XMLHTTP.5.0",
    "video",
    "(near '... null[0]...')",
    "u<02N<np/~|v",
    "VERTEX_SHADER",
    "Decrypt Ajax Response Failed",
    "responseURL",
    "double",
    "MicroMessenger",
    "vlaue",
    "substring",
    "alert",
    "}7jqemycxg*ncujF7jqemycxg*ncuj",
    "jbscheme://queue_has_message",
    "defaultPrevented",
    "wifi",
    "nodeName",
    "image",
    "; Secure",
    "SetRequestHeader",
    "iframe",
    "clientInformation",
    "MEDIUM_FLOAT",
    "volatile",
    "kIM9jbXIM9jb",
    "clientY",
    "od}asjTDuq|B|qkud 9X 5a~fda|TW",
    "transaction",
    "const",
    "vertexPosAttrib",
    "layerX",
    "super",
    "head",
    "mgd{_zcc}wvTacn5b{ash{cbGhsfhH{awTacn=bvwlwv86TacnFweiwgh5b{ash{cb:fsaw",
    "clearInterval",
    "safari",
    "disabled",
    "jbscheme://",
    "arity",
    "import",
    "HTMLObjectElement",
    "0000",
    "position",
    "createBuffer",
    "qrcklmDoExthWJiHAp1sVYKU3RFMQw8IGfPO92bvLNj.7zXBaSnu0TC6gy_4Ze5d{}|~ !#$%()*+,-;=?@[]^",
    "cY#rDABASAnA0ATA61Xs<s>VwR;FnF$F%F MqM8MIMGQqQhQWQHQAQpQMQbQvQ^Q&Q*wvw7wzwnwuwZ8c8k8o8s8V8Y8.IqIrIcIlImIDIMIQI_I4IZGQG8GIGGGvGLG-G7GzGCG6G@G$fxf^f&f*f(f)f}PmOjO-O6OgO|O 9g9_949@9$9%9&9*9(9)9:9;2m2D222bbUbfb7bzb<b>v4v*LtLhL)jUjfjP-2-b-@-%-&-=-<7u7_74zfXzXXXuX_X4XZXeX5XdX~X BqBrBcB-B7BzBXBBBCBgB&6~$o$E$v$L%1%P%O%9%y&{(I(G(L(N(j+i+H=l=m=@=$=%=>=.=?=/=:<s>d.K.U.w.8.9.2.b?x?t?h?j?B?a?S?n?u:h:W:J:i{D{1{U#!#rkArkprk$rk%rk rmurn&rn*mf!mf.mf?mOAmOpmbUmbMmbGmbgmbymb_mb4mbZmvZmvemLvmjkmjlmj0m-hm-Wm-Jm-1m-sm-Vm7Xm7Bm7am7Sm7nm7um70m7Tm7@m7=m7<mzfmz]mXlmXmmXhmXWmXimS2mSbmSvmSLmSNmSjmS-mS7mSXmSBEtQEsAEspEKp",
    "package",
    "multipart/form-data",
    "try{return (window instanceof Window);}catch(e){}",
    "b$gnnj$+$$knffdq+$$kro+$$krqa+$gcw$+$qd~cxBncd@kqd~cxDwdbtsdcHmSghrEq~ld+$rcw$+$thd$",
    "toLowerCase",
    "[object Array]",
    "fillRect",
    "TK_NUMBER",
    "Msxml2.XMLHTTP",
    "setLocalDescription",
    "alpha",
    "<span style=\"font-family:mmllii;font-size:114px\">mmmmmmmmmmmlliii</span>",
    "bufferData",
    "complete",
    "enctype",
    "TRIANGLE_STRIP",
    "Infinity",
    "numItems",
    "charAt",
    "responseBody",
    "Msxml3.XMLHTTP",
    "meta",
    "met_tf{vywTettcc}gzw~x",
    "debugger",
    "radio",
    "fontFamily",
    "firstChild",
    "Float32Array",
    "cookieEnabled",
    "setTime",
    "RTCPeerConnection",
    "rows",
    "getAttribLocation",
    "random",
    "audio",
    "oEawag",
    "touchend",
    "acceleration",
    "keyup",
    "pushNotification",
    "anchor",
    "split",
    "onbeforeunload",
    "parent",
    "detachEvent",
    "text",
    "mimeTypes",
    "$b_setup",
    "$_fb",
    "internal",
    "addBehavior",
    "Object.InjectedScript.evaluate",
    "toFixed",
    "n4x6bageb}U4x6bageb}",
    "Abort",
    "unescape",
    "mouseUp",
    "DispatchEvent",
    "getShaderPrecisionFormat",
    "credentials",
    "unload",
    "TK_REG_EX",
    "bgsound",
    "p-~qytre xs.\"qq)Wzy\" r{pddxs.\"r{dxs+XUZUu)V*R*)qZRVVruRqq)WRUUppUUqsrtUq\" hxsew.\"Uai\" wtxvwe.\"Uai\"/-T~qytre/",
    "setServerData",
    "item",
    "RegExp",
    "case",
    "srcElement",
    "description",
    "onautocomplete",
    "\\b[^>]*>([\\s\\S]*?)<\\/",
    "level",
    "chrome",
    "save",
    "sya1~qpqzbumxa",
    "options",
    "Request",
    "attrVertex",
    "except",
    "pixelDepth",
    "isNaN",
    "overrideMimeType",
    "PointerEvent",
    "sessionStorage",
    "lastIndexOf",
    "documentElement",
    "decodeURIComponent",
    "mousemove",
    "charset",
    "url(#default#userdata)",
    "utf-8",
    "mozConnection",
    "accelerationIncludingGravity",
    "onupgradeneeded",
    "result",
    "webkitIndexedDB",
    "orientation",
    "globalStorage",
    "gamma",
    "contains",
    "Response-Type",
    "var getAttribute=function(name){return cur_ele.getAttribute(name);};",
    "OBJECT",
    "transferChannel",
    "prop",
    "ownerDocument",
    "indexedDB",
    "r[#Egx.W|JcArAzpvpS1x1Qs4s!s%s)s?s;VZV]KqKtK^K>UUUFUQU9UbULUjUXR?R:F0FCF6F5FdF@F*F=QcQlQmQEwNw-wCwg8/8;8{8|GfG9f>f?f:f{PBPSOsOYOKOROMOwOIOP9Z9~bEbtbhbibAb1bVbKv~v@v$v^v)v/L<L;NDNJjFjIjXju727n707g7%7=7>zUXBXnX0XyBoBxBhBJBABKBFBwBaBTB$B^@G@P@~@@%s%R%F%f%2%B^i^A(3(F(M(8(f(O(-(a(S(u)?+D=D=E=^===;<q<r<D<o<A>4>5.3.Q.I.O.>.[?-?X/}:c:k:t;.;/;;{m{o{J[u]q]U]R#P#rmPrmXrm6rm@rLKrL3rj[r-MrSarSTmLUmLbmL$mL}mNamN6mN:mjcmjSmjum-im-pm-Ym-3m7Lm7zmz mXrE1CE1^E1]EskEsjEs7",
    "Unexpected token: ",
    "Element",
    "Send",
    "; path=/",
    "mouseMove",
    "length",
    "XMLHttpRequestEventTarget",
    "constructor",
    "return a[b](",
    "]><i></i><![endif]-->",
    "$_f1",
    "lineno",
    "getServerDataInCookie",
    "GetVariable",
    "referrer",
    "deviceId",
    "u}ovoxsaw",
    "then",
    "QQBrowser",
    "HIGH_INT",
    "POST",
    "error",
    "return",
    "message",
    "FSSBB",
    "cfn_gbclrgdgcp",
    "byte",
    "/T7AyTrxoWxGd",
    "implements",
    "substr",
    "offsetX",
    "FSSBA",
    "{i|mx,yppwgviir",
    "Only one variable declaration allowed in for..in loop",
    "runtime",
    "Number",
    "fillText",
    "$b_onNativeResponse",
    "close",
    "data",
    "unobsmowy~syx",
    "<meta\\s+http-equiv=[\"']?refresh[\"']?\\s",
    "readwrite",
    "18px 'Arial'",
    "width",
    "(this);",
    "mouseover",
    "content",
    "$bmF0aXZlRmlVyUHJ",
    "encoding",
    "static",
    "~dbmm3iboupnC_qiboupn",
    "f|z|c~_",
    "checkbox",
    "toUpperCase",
    "hostname",
    "float",
    "use strict",
    "Please enable cookie in your browser before you continue.",
    "keyDown",
    "<!--",
    "rangeMax",
    "removeItem",
    "extends",
    "document-fragment",
    "$_fr",
    "touchmove",
    "boolean",
    "delete",
    "MEDIUM_INT",
    "([0-9]{1,3}(\\.[0-9]{1,3}){3}| (([0-9a-f]{1,4}:){7,7}[0-9a-f]{1,4}|([0-9a-f]{1,4}:){1,7}:|([0-9a-f]{1,4}:){1,6}:[0-9a-f]{1,4}|([0-9a-f]{1,4}:){1,5}(:[0-9a-f]{1,4}){1,2}|([0-9a-f]{1,4}:){1,4}(:[0-9a-f]{1,4}){1,3}|([0-9a-f]{1,4}:){1,3}(:[0-9a-f]{1,4}){1,4}|([0-9a-f]{1,4}:){1,2}(:[0-9a-f]{1,4}){1,5}|[0-9a-f]{1,4}:((:[0-9a-f]{1,4}){1,6})|:((:[0-9a-f]{1,4}){1,7}|:)|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-f]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])) )",
    "___ts___",
    "candidate",
    "void",
    "opener",
    "port",
    "Count",
    "uniform2f",
    "getBattery",
    "getTimezoneOffset",
    "contextmenu",
    "loaded",
    "serverData",
    "yield",
    "offsetLeft",
    "b~ookhb~shnm.w,rgnbjv~ud,ek~rg",
    "parseInt",
    "Unexpected character: ",
    "charging",
    "mousedown",
    "yxsui~J:kgr8rgakx /N +utzxur",
    "synchronized",
    "timeout",
    "Microsoft.XMLHTTP",
    "e~khldej(~khldejejbk(~khldejiap{",
    "typeof",
    "mouseup",
    "Z8XHj",
    "CREATE TABLE IF NOT EXISTS EkcP_t (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, value TEXT NOT NULL, UNIQUE (name))",
    "text/javascript",
    "insertBefore",
    "preventDefault",
    "i__ILH__@GGC_FGLA>A=J",
    "behavior",
    "Unenclosed regular expression.",
    "shenjian",
    "screenX",
    "webgl",
    "true",
    "javascript:",
    "Unexpected token ",
    "webkitConnection",
    "height",
    "Msxml2.XMLHTTP.6.0",
    "Msxml2.ServerXMLHTTP.3.0",
    "getSources",
    "AddSearchProvider",
    "/:user_fonts",
    "Open",
    "elements",
    "bluetooth",
    "~xfcesjwfs",
    "else",
    "onsuccess",
    "capture",
    "vertexAttribPointer",
    "{__gv=ifF__k)v=if",
    "[native code]",
    "TEMPORARY",
    "qrcklmDoExthWJiHAp1sVYKU3RFMQw8IGfPO92bvLNj-7zXBaSnu0TC6gy_4Ze5d~!@$%^&*()+=<>.?/:;{}[]| ",
    "PerformanceObserver",
    "datas-ts",
    "getExtension",
    "linkProgram",
    "MSPointerEvent",
    "return new a(",
    "p|~kgxdxqx{xejrwp}vt",
    "javascript: void(0);",
    "getItem",
    "$_YWTU",
    "replaceState",
    "bb82kj",
    "useProgram",
    "kGk}waJ}cyXGk}waJ}cy",
    "include",
    "drawArrays",
    "continue",
    "createShader",
    "cBDNfcjtcrga}9Rg~cr}l K}afglc Slg9Ammjh}xx9Tcpb}l}9Fcjtcrga} Lcsc JR Npm 13 Rfgl9r}fmk}9JE Qk}pr_F rcqr Pcesj}p9BGLNpm+jgefr9Fcjtcrga} JR 21 Jgefr Cvrclbcb9FcjtcK_Glbg}9QCAPm~mrmJgefr @mjb9MP Kmf}lrw Slgambc Pcesj}p9Bpmgb Q}lq Rf}g9I}ll}b} Q}le}k KL9BBA Safcl9ajmai0./4_t/,/9Q}kqsleI}ll}b}Pcesj}p9KG J?LRGLE @mjb9Q}kqsleQ}lqLsk1J Jgefr9tcpb}l}9Fcjtcrga}LcscRfgl9QCAD}jj~}ai9Q}kqsleCkmhg9Rcjses Q}le}k KL9A}ppmgq Emrfga QA9Djwkc Jgefr Pm~mrm Jgefr9QmK?+Bgegr Jgefr9QmKA Q}lq Pcesj}p9FWVgWs}lH9qqr9q}kqsle+q}lq+lsk2R9ek_kclekcle9Jmfgr I}ll}b}9rgkcq lcu pmk}l9q}kqsle+q}lq+lsk2J9qcpgd+kmlmqn}ac9Q}kqsleQ}lqLsk+1R Rfgl9AmjmpMQSG+VRfgl9Bpmgb L}qif Qfgdr ?jr9Q}kqsleRcjsesPcesj}p9@cle}jg MRQ9KG J}lRgle_E@ Msrqgbc WQ9DXKg}mUs_E@/6.1.9fcjtc+lcsc+pcesj}p9QQR Kcbgsk9Amspgcp Lcu9Ifkcp Kmlbsjigpg @mjb9Fcjtcrga} JR 01 Sjrp} Jgefr Cvrclbcb9Fcjtcrga} JR 03 Sjrp} Jgefr9Pm~mrm Kcbgsk9Bpmgb Q}lq @mjb9emsbw9q}lq+qcpgd+amlbclqcb+jgefr9QDglbcp9lmrm+q}lq+ahi+kcbgsk9kgsg9KPmaiw NPA @mjb9?lbpmgbAjmai Pcesj}p9Q}kqsleQ}lqLsk+2J Jgefr9q}lq+qcpgd+rfgl9?}N}leW}cp9a}qs}j9@L Kmf}lrwMR @mjb9v+qqr9LmrmQ}lqKw}lk}pX}uewg9Fcjtcrga} JR 11 Rfgl Cvrclbcb9?qfjcwQapgnrKR ?jr9Lmrm Q}lq Bct}l}e}pg SG9Pm~mrm Amlbclqcb @mjb9Pm~mrm Kcbgsk Gr}jga9kgsgcv9Lmrm Q}lq Espksifg SG9QQR Tgcrl}kcqc Jgefr9JE_Mpgw}9fwamddcc9v+qqr+sjrp}jgefr9BDFcg?U5+?9DXXUV@RMR_Slgambc9Bct}l}e}pg Q}le}k KL @mjb9q}lq+qcpgd+kmlmqn}ac9N}b}si @mmi @mjb9JE+DXWgle@gI}gQfs+Q/3+T0,09JE+DXWgle@gI}gQfs+Q/3+T0,19Fcjtcrga}LcscJR Npm 13 Rf9Kgapmqmdr Fgk}j}w}9Q}kqsleQ}lqD}jj~}ai9QQR Kcbgsk Gr}jga9?lbpmgbCkmhg9Q}kqsleQ}lqLsk+1P9GRA Qrmlc Qcpgd9q}lq+qcpgd+qk}jja}nq9v+qqr+kcbgsk9JE_Qglf}jcqc9Pm~mrm Rfgl Gr}jga9aclrspw+emrfga9Ajmaimng}9Jskglmsq_Q}lq9Djmpgbg}l Qapgnr ?jr9Lmrm Q}lq Espksifg @mjb9JRFWQXI @mjb9EQ_Rf}g9Q}kqsleLcmLsk_1R_09?p}~ga9f}lq+q}lq+lmpk}j9Jmfgr Rcjses9FWOgFcg+3.Q Jgefr9Jglbqcw dmp Q}kqsle9?P Apwqr}jfcg B@9Q}kqsle Q}lq Kcbgsk9q}kqsle+q}lq+lsk239f}lq+q}lq+~mjb9Jskglmsq_Qapgnr9QQR Amlbclqcb9Q}kqsleBct}l}e}pgPcesj}p9?lh}j K}j}w}j}k KL9Q}kqsleRf}gZrcqr[9DXJ}lRgleFcg+K+E@/6.1.9Fc~pcu MRQ9EQ23_?p}~Z?lbpmgbMQ[9Q}kqsle Q}lq Jgefr9Afmam ammiw9fcjtc+lcsc+rfgl9NL Kmf}lrwMR Kcbgsk9JE+DXI}Rmle+K/7+T0,29Bpmgb Qcpgd9Q}kqsleQglf}j}Pcesj}p9fcjtcrga}9JE+DXI}Rmle+K/7+T0,09Lmrm Q}lq Bct}l}e}pg SG @mjb9QQR Jgefr9BDNCkmhg9uc}rfcpdmlrlcu Pcesj}p9Pm~mrmLsk1P9BGLNpm+kcbgsk9Q}kqsle Q}lq Lsk339QQR Fc}tw Gr}jga9JEjmai2 Pcesj}p_.6.39Ecmpeg}9lmrm+q}lq+ahi9Rcjses Q}le}k KL @mjb9KGSG CV Lmpk}j9FWOgFcg+53Q @mjb9LmrmQ}lqKw}lk}pX}uewg @mjb9wslmqnpm+~j}ai9fcjtc+lcsc+lmpk}j9Jskglmsq_Qcpgd9RK Kmf}lrwMR Lmpk}j9Q}kqsleQ}lqLsk+1Jt Jgefr9Q}kqsle Q}lq Lsk239Qk}prEmrfga Kcbgsk9ecmpeg}9a}qs}j+dmlr+rwnc9Q}kqsle Q}lq @mjb9qk}jj+a}ngr}jq9KDgl}lac NPA @mjb9DXJ}lRgleFcg_E@/6.1.9Q}kqsle?pkclg}l9Pm~mrm @mjb9aclrspw+emrfga+~mjb9v+qqr+fc}tw9QQR Jgefr Gr}jga9Rf}pJml9v+qqr+jgefr9Bgl~mj Pcesj}p9Q}kqsle@cle}jgPcesj}p9IL Kmf}lrwMRQk}jj Kcbgsk9fwnspc9Q}kqsleR}kgjPcesj}p9K}j}w}j}k Q}le}k KL9Lmrm Q}lq I}ll}b} SG9fcjtc+lcsc9Fcjtcrga} JR 33 Pmk}l9Lmrm Q}lq I}ll}b} @mjb9Q}lnw}9Q}kqsleNslh}~gPcesj}p9q}kqsle+q}lq+lsk2Jt9JE_I}ll}b}9Q}kqsle Q}lq Pcesj}p9X}uewg+Mlc9Bpmgb Qcpgd @mjb Gr}jga9DXI?RHU9amspgcp lcu9Q}kqsleCkmhgPcesj}p9KGSG CV @mjb9?lbpmgb Ckmhg9Lmrm L}qif ?p}~ga SG9JAB Amk9Dsrsp} Kcbgsk @R9Tgtm+cvrp}ar9@}lej} Q}le}k KL @mjb9f}lq+q}lq+pcesj}p9QLsk+1P9QLsk+1R9f}lq+q}lq9QQR Sjrp} Jgefr9Pm~mrm Pcesj}p9Pm~mrm Jgefr9F}lsk}l9lcujeemrfga9BDFcg?U3+?9f}lq+q}lq+jgefr9Nj}rc Emrfga9QLsk+1J9Fcjtcrga} JR 23 Jgefr9Kw}lk}p Q}le}k X}uewg @mjb9je+q}lq+qcpgd+jgefr9KGSG CV Jgefr9Pm~mrm Rfgl9QmK? @mjb9N}b}si9Q}kqsle Q}lq9Qn}agmsq_Qk}jjA}n9q}lq+qcpgd9BT Kmf}lrwMR Kcbgsk9Qr}~jc_Qj}n9kml}am9Djwkc+Jgefr9dxxwq+bmqnw9QapcclQ}lq9ajmai0./49Pm~mrm Amlbclqcb @mjb Gr}jga9?pg}j9IL Kmf}lrw Kcbgsk9Kmrmw}JK}ps U1 kmlm9F}lbqcr Amlbclqcb9Pm~mrm Gr}jga9FRA F}lb9QQR Sjrp} Jgefr Gr}jga9QQR Tgcrl}kcqc Pmk}l9Lmrm L}qif ?p}~ga SG @mjb9afldxvf+kcbgsk9QLskAmlb+1R9aclrspw+emrfga+pcesj}p9bcd}sjr_pm~mrm+jgefr9Lmrm Q}lq Kw}lk}p9Kw}lk}p Q}le}k KL9?nnjc Amjmp Ckmhg9uc}rfcpdmlrPce9Q}kqsleK}j}w}j}kPcesj}p9}pg}j9Bpmgb Qcpgd @mjb9ANm1 NPA @mjb9KG J?LRGLE9Q}kqsleImpc}l+Pcesj}p9rcqr23 Pcesj}p9qngpgr_rgkc9Bct}l}e}pg Q}le}k KL9QapcclQcpgd9Pm~mrm9aspqgtc+dmlr+rwnc9QRFcgrg_tgtm9afldxvf9Q}kqsle AjmaiDmlr 1?9Pm~mrm Amlbclqcb Pcesj}p9q}kqsle+lcm+lsk1P9EH Kmf}lrwMR Kcbgsk9Afsjfm Lcsc Jmai9pm~mrm+lsk1J9fcjtc+lcsc+sjrp}Jgefrcvrclbcb9Q}kqsleMpgw}Pcesj}p9Q}kqsleQ}lqLsk+2Jt Jgefr9KWgleFcg_/6.1._A0+@mjb9BDNQf}mLtU3+E@9Pm~mrm @j}ai9fcjtc+lcsc+sjrp}jgefr9ek_vgfcg9JEjmai2 Jgefr_.6.39Esh}p}rg Q}le}k KL9K}j}w}j}k Q}le}k KL @mjb9pm~mrm+lsk1P9QRVgfcg_tgtm9DXXfslWs}l_E@/6.1.9lmrm+q}lq+ahi+jgefr9amjmpmq9Lmrm Q}lq Espksifg9Lmrm Q}lq Qwk~mjq9Pm~mrm Jgefr Gr}jga9Jmfgr R}kgj9aspqgtc9bcd}sjr_pm~mrm9@f}qfgr}AmknjcvQ}lq @mjb9JE_Lsk~cp_Pm~mrm Rfgl9kmlmqn}acb+ugrfmsr+qcpgdq9Fcjtcrga} JR 13 Rfgl9q}kqsle+q}lq+lsk1JT9BGLNpm9Hmkmjf}pg9q}lq+qcpgd+jgefr9fcjtc+lcsc+~j}ai9Jmfgr @cle}jg9Kw}lk}p Q}le}k X}uewg9Bpmgb Qcpgd Gr}jga9Pm~mrm @mjb Gr}jga9L}lskEmrfga9Qmlw Km~gjc SB Emrfga Pcesj}p9Ecmpeg} @mjb Gr}jga9q}kqsle+q}lq+lsk1Jt9wslmq+rfgl9q}kqsle+lcm+lsk1R+amlb9Lmrm Q}lq Kw}lk}p SG @mjb9jeqcpgd9DXWmsFcg+P+E@/6.1.9Jmfgr Nslh}~g9~}qicptgjjc9q}kqsle+q}lq+lsk2Rt9q}kqsle+q}lq+rfgl9JE Ckmhg9?lh}jgLcuJgng9Q}kqsleQ}lqLsk+2R Rfgl9Q}kqsleImpc}l+@mjb9kgsgcv+jgefr9Lmrm Q}lq I}ll}b}9Pm~mrm Lmpk}j Gr}jga9Ecmpeg} Gr}jga9q}lq+qcpgd+kcbgsk9Qk}pr X}uewg9Pm~mrm Amlbclqcb Gr}jga9Lmrm Q}lq I}ll}b} SG @mjb9BDN Qa Q}lq Fcsc1._/.19JE_Lsk~cp_Pm~mrm @mjb9N}b}si @mmi9v+qqr+amlbclqcb9Qslqfglc+Safcl9Pm~mrm @j}ai Gr}jga9Pglem Amjmp Ckmhg9Bct}l}e}pg MRQ9Qk}pr X}uewg Npm9DXJ}lRgleFcg+K+E@I9?lbpmgbAjmai+J}pec Pcesj}p9npmnmprgml}jjw+qn}acb+ugrfmsr+qcpgdq9Asrgtc Kmlm9rgkcq9JE Qk}pr_F rcqr @mjb9BGLNpm+Jgefr9q}lq+qcpgd+~j}ai9Jmfgr Bct}l}e}pg9npmnmprgml}jjw+qn}acb+ugrf+qcpgdq9q}kqsle+q}lq+lsk1J9KWmsle NPA Kcbgsk9BDEmrfgaNU3+@GE3FI+QMLW9f}lq+q}lq+kcbgsk9QQR Fc}tw9JE+DXXfslWs}l+K.0+T0,09Kw}lk}pSLcu Pcesj}p9Lmrm L}qif ?p}~ga @mjb9Q}kqsleEsh}p}rfgPcesj}p9d}lr}qw9fcjtc+lcsc+jgefr9Fcjtcrga} Lcsc MRQ @mjb9lmrm+q}lq+ahi+~mjb9q}kqsle+q}lq+lsk1P9Jglbqcw Q}kqsle9q}kqsle+q}lq+lsk1R9QapcclQcpgdKmlm9CRpskn Kw}lk}p_XU9fcjtc+lcsc+rfglcvrclbcb9Lmrm L}qif ?p}~ga9JE_Esh}p}rg9Qk}pr_Kmlmqn}acb9R}kgj Q}le}k KL9JE Ckmhg Lml?KC9Pm~mrm Amlbclqcb Jgefr Gr}jga9ek_hglei}g9DXJ}lRgleI}lFcg_E@/6.1.9jerp}tcj9n}j}rglm9Ecmpeg} @mjb9Bpmgb Q}lq9JE_Nslh}~g9Qk}prEmrfga @mjb9Q}kqsle Q}lq Rfgl9QQR Amlbclqcb @mjb9Amkgaq_L}ppmu9amspgcp9Mpgw} Q}le}k KL9fcjtc+lcsc+jgefrcvrclbcb9DXJ}lRgleFcg+P+E@/6.1.9?P Apwqr}jfcgFIQAQ B@9qcpgd9PRUQWscPmsbEmE.t/+Pcesj}p9Kg}mUs_npct9DXW/I9JE_Lsk~cp_Pm~mrm Pcesj}p9?lbpmgbAjmai9QmK? Pcesj}p9FWOgFcg+2.Q Jgefrv9je+q}lq+qcpgd9B}lagle Qapgnr @mjb9bcd}sjr9qca+pm~mrm+jgefr9AmjmpMQSG+Pcesj}p9rcqr Pcesj}p9R}kgj Q}le}k KL @mjb9DXWgle@gVgleQfs+Q/49Pm~mrmLsk1J Jgefr9kmlmqn}acb+ugrf+qcpgdq9q}kqsle+q}lq+lsk139Ammj h}xx9Q}kqsleLcmLsk+1J9QRVglei}g9QapcclQ}lqKmlm9BDNU}U}U3+E@9Q}kqsleQ}lqLsk+1J Jgefr9@}lej} Q}le}k KL9Espksifg Q}le}k KL9QCAPm~mrmJgefr9fwdmlvp}gl9KWgleFcgE@/6.1.A+@mjb9q}kqsle+q}lq+jgefr9Fcjtcrga} JR 43 Kcbgsk9Bpmgb Q}lq D}jj~}ai9Pm~mrm Rcqr/ @mjb9Lmrm Q}lq Kw}lk}p @mjb9q}lq+qcpgd+amlbclqcb+asqrmk9Q}kqsleLcmLsk+1R9Q}kqsle Q}lq Lsk139kmlmqn}ac9RJ Kmf}lrw Kcbgsk9fcjtc+lcsc+kcbgsk9JRFWQXI9Pm~mrm Amlbclqcb asqrmkc @mjb9Kw}lk}p19Bpmgb Q}lq Bct}l}e}pg9Qf}mLt_npct9q}kqsle+lcm+lsk1J9DXJ}lRgleFcg+CJ+E@I9wslmq9q}kqsle+lcm+lsk1R9Rgkcq Lcu Pmk}l9fcjtc+lcsc+~mjb9lmrm+q}lq+ahi+pcesj}p9Lmrm Q}lq Espksifg SG @mjb9BGLNpm+~j}ai9DXJ}lRgleFcg+CJ+E@/6.1.9QQR Tgcrl}kcqc Kcbgsk9Pm~mrm Amlbclqcb Jgefr9QQR Tgcrl}kcqc @mjb9?P BH+II9Bpmgb Q}lq QCKA9Lmrm Q}lq Kw}lk}p SG9Amkgle Qmml9KWsnnw NPA Kcbgsk9Pmqck}pw9Jmfgr Esh}p}rg9Pm~mrm Amlbclqcb asqrmk @mjb9DXJ}lRgleFcgQ+P+E@9Fcjtcrga} Lcsc MRQ9I}grg_npct9Pm~mrm+@geAjmai9DXW@IQHU9F}lbqcr Amlbclqcb @mjb9Q}kqsleEcmpeg}l9B}lagle Qapgnr9q}lq+qcpgd+amlbclqcb9f}lq+q}lq+rfgl9Q}kqsleQ}lqLsk+2Rt Rfgl9Jmfgr Mbg}9@f}qfgr}AmknjcvQ}lq",
    "isFinite",
    "$_vvCI",
    " host ",
    "layerY",
    "t?plwCtopzO?plwCtopzIaxJ .natcpE 0zya}zw ITSNmtaJ",
    "qrbwfsb",
    "host",
    "history",
    "origin",
    "FLOAT",
    "\\\\",
    "mouseOver",
    "try{return __dirname;}catch(e){}",
    "textarea",
    "fillStyle",
    "Missing catch/finally blocks",
    "short",
    "text/html",
    "ceil",
    "$b_callHandler",
    "preload",
    "selected",
    "OPEN",
    "fromCharCode",
    "returnValue",
    ">>>=",
    "mozItems",
    "dumpAll",
    "rR#r:ckcEE9Ebx[x]tWt1HP171zs_s+s=s{s}VhVQKhK.K?K}FuF&MiMHM7MzM?QrQ1QGQfQ0QTQ{Q}www8wGwfwOw9w)8%8^8?IxIRIFI(I)G1GsGwGZGeG:ftfGfffOf2fbfjf-f|O1OzOXOTOC9y2r2k2lbobjb-vXL+L=N~N!N$N&N*N)N<jhjJjAjpj3jRjOj7j@j$-JX!BtBiBHB6a<0%T{%u%g&}?6?g#2#rrHrrprrsrcMrlQrljrm}rDqrDirDwrDIrDfrD*roOro9rNer-=rShrSWrS!rS@rZuczXcXGmiamG[mG]m9;m9{mS@D]UEtMEtZEt5EtdEt!Et@",
    "parse",
    "Entity",
    "frames",
    "getAllResponseHeaders",
    "finally",
    "LOW_FLOAT",
    "escape",
    "jdjm~j~w~c~kpx}ve|z",
    "PerformanceObserverEntryList",
    "post",
    "@debugger",
    "Msxml2.ServerXMLHTTP.5.0",
    "HIGH_FLOAT",
    "colorDepth",
    "$_ts",
    "rgba(240,110,53,0.4)",
    "var submit=function(){for(var t=cur_ele;t!==document&&(!t.tagName||\"form\"!==t.tagName.toLowerCase());)t=t.parentElement;t!==document&&t.submit()};",
    "originalTarget",
    "fetch",
    "attributes",
    "OverrideMimeType",
    "getSupportedExtensions",
    "forEach",
    "|7hdo5od|hu",
    "ethernet",
    "stopPropagation",
    "DeviceMotionEvent",
    "}$4tg9[Ztqyugt[ncuukeD9[Ztqyugt1guucig[gpvgt",
    "\u0000",
    "mouseOut",
    "interface",
    "touches",
    "Msxml2.ServerXMLHTTP.4.0",
    "catch",
    "http-equiv",
    "switch",
    "th\\~K\\Hylatcp nzop\\]\\~Kj",
    "Name expected",
    "outerHTML",
    "screenY",
    "cancelBubble",
    "evaluate",
    "mouseDown",
    "getContext",
    "cygJ+",
    "Gamepad",
    "fontList",
    "Unenclosed string.",
    "default",
    "<EMBED id=",
    "webstore",
    "o}al:yttu~",
    "acos",
    "$_vJTp",
    "objectStore",
    "__#classType",
    "dispatchEvent",
    "tests",
    "Submit",
    "data:",
    "JSON",
    "uniformOffset",
    "nextSibling",
    "while",
    "enumerateDevices",
    "absolute",
    "y^\\$CgIb]ji_",
    "HTMLAnchorElement",
    "false",
    "toGMTString",
    "﻿",
    "x__t{{,ylh{l/yhtlIt{{,|tz{vt3<",
    "performance",
    "mozRTCPeerConnection",
    "public",
    "sp~udq~Oqdmxcmbq",
    "setClientData",
    "|zhenlwylvlelolw|fkdqjh",
    "toDataURL",
    "exec",
    "getClientDataInCookie",
    "createDataChannel",
    "DeviceOrientationEvent",
    "</$1",
    "applicationCache",
    "class",
    "var cur_ele = this;",
    "canvas",
    "r#!#c #rrrErfcic9cbc%c&o;o|ExE3EQx?x{tqtktitAtVtvtNhPh9W[Jmi^i{HIHjH/A~prpopxpg1E1BsgVDVEV8V4YqY K9K%R{FBF.F|M3MQMPMNMaM^M*M>M{M]QOQ2Q)Q.Q|wswYwMw%w*8l8D8U8I8f8O828_8Z8@8*8=I5I^I<GEGtGAGYGRGdG!fWfpfYfUfRfQfBfSfTf~PuP_PZP5P~P]P OEOtOi9r9E9t9W9i999b9B9S9T2L2B2S2u2T2=2>bkb%b)b?vovhvPv9v7vSv6LRL(L NmN{N]N jmjojxjsjKjbjj->-}-]7G7Z7dXcX7X;X|BkBDBUBRB8BjB)aYaGa+a/S/S]n~n&u5u^000C0y0Z0@0&0)0<TMTwTGTOT$T^T(T=T:T[T CcCAC1C+C<C?C;64gEgUgLyOya~7~B~C~!!r!o!:@i@F@Q@I@X@d@.$D$Y$f$O$2$T%H^O&f&j&;*:(V(()W)H)s)I)(+o+J+&=k>~.Y.v.z?W?N/a/{:9:b:S:}{2[n]F#r]#rq9rqvrq7rqBrq}rq|rrkrrDrrJrrYrrurrCrcprcsrcRrcIrcfrcOrcNrczrcarcurcgrcerc)rc?rc:rc{rkqrl4rldrDkrDWrD1rDKrDOrDbrDLrDnrDTrDgrD5rD@r2nrborbxrb6rbyrb(rb+rb]rvqrLhrLvrL<rL|rNurN.rjhrjYrjMrjwrjOrj2rj-rjzrjurjTrj4rjerj$rj^rj=rj>rj{rS6rS4rS*rn$rn+rn<rn.ru.ru/ru{r0qr0Lr07rTarT@rCqrCyrC(mHVmQMmwCmG6mG4mG+mf1mfSmf0mf~mf:mPAmO6mOdmO@m9?mbAmbKmb3mbFmbQmbImbfmb6mb[mvBmv5mLKmNVmNBmN_mN/m- m7vm7dm7!m7$m7+ElVEoCEoyEEFEEGExaEx|EtlEtpEtYEtwEtbEtLEt0EtCEt_Et%Eh]EWIEA2EAgEp8EpfEp]E1bE1SEs>Es:Es{EYvEY<EKWEKsEK7EKgEU6EU4EU~EU$EU(EU=EU/EU{EU[",
    "d_Pbibkfrj_FAB_Ob~loabo)_pbibkfrj)~|iiPbibkfrj",
    "enum",
    "setItem"
];

traverse(ast, {
    MemberExpression(path) {
        var node_ = path.node;

        var mem_name = node_.object.name;

        if (mem_name === "_$v4") {
            path.replaceWith(t.stringLiteral(parse_obj[node_.property.value]))

        }
    }
})

// traverse(ast,{
//     TryStatement(path){

//         var node_ = path.node;
//         var block = node_.block;
//         var block_body = block.body;
//         var try_parent = path.parent;

//         var parent_body = try_parent.body;

//         for (var i in parent_body){
//            if ( parent_body[i].type =="TryStatement"){
//                 if (block_body.length==1){
//                     parent_body[i] = block_body[0];
//                 }else{
//                     var cache = 0;
//                     for (var j=block_body.length; j>=0;){
//                         --j
//                         if (j == (block_body.length-1)){
//                             parent_body[i] = block_body[j];
                            
//                         }else{
//                             cache += 1;
//                             let cache_index = i-cache;
//                             if (cache_index <= 0){
//                                 parent_body.unshift(block_body[j]);
//                             }else{
//                                 parent_body[cache_index] = block_body[j];
//                             }
                            

//                         }
//                     }

//                 }

                

//            }

//         }

//         // return


//     }

// })


let new_code = generator(ast).code;


fs.writeFileSync('./ruishu_new_2.js', new_code, { encoding: 'utf8' })